### ISSUE TITLE
SpuInit locks up in certain emulators in SpuCtrlSync

### ISSUE THREAD

**Issue by thp** [Lameguy64/PSn00bSDK#15]
Calling `SpuInit();` at the beginning of a program seems to lock up in certain official emulators.

If I comment out both calls to `SpuCtrlSync` in that function, it seems to work (on the emulator at least, haven't tested on real hardware yet):

Interestingly, the `SpuWrite` function has a similar comment:

```
        #jal            SpuCtrlSync                             # Locks up on most emulators (bit 5 in
        #move   $a0, $v0                                        # SPUSTAT likely not updating, seems to
                                                                                # be okay to not wait for it on real HW)
```

Not sure if it helps or is related at all, but I found this while doing a random web search:

> NB. writing the SAME transfer mode value to SPUCNT does mean that one cannot sense when the write gets applied (since SPUSTAT already contained that same transfer mode setting), so, instead, one must use some hardcoded delay (the BIOS is performing some crazy super-slow delay for that purpose... but I guess that a delay of one 44100Hz cycle (around 300h clks) should be enough). [[source link](https://www.ngemu.com/threads/feature-request.159967/)]

**Comment by thp** [comment]
By the way, I tried it on a real PAL PS1 this weekend and both versions (the one with the sync calls and the one without the `SpuCtrlSync` call) work fine.

**Comment by Lameguy64** [comment]
The purpose of SpuCtrlSync() is to wait for bits 0-5 of the SPUSTAT register to become equal to bits 0-5 of the SPUCTRL register. Reason being is that changes to the SPUCTRL register are delayed and this check makes sure the changes have applied before continuing execution. I'm considering taking a closer look at it however.

**Comment by wheremyfoodat** [comment]
Fixed this on an emulator where it was broken - merely making SPUSTAT[5:0] a mirror of SPUCNT[5:0] will work. There's a small delay on hardware, but it's not very important to emulate. This should definitely work on real PS1 hardware.
Is it possible to name some emulators where this is broken? I'm sure the authors would appreciate being told.

**Comment by thp** [comment]
It was one of the "official" POPS emulators on Sony hardware, so probably not really easy to get those fixed ;)

**Comment by wheremyfoodat** [comment]
Oh, yeah. That sounds hilarious, but also kind of a lost cause.

**Comment by spicyjpeg** [comment]
[A timeout was added](https://github.com/Lameguy64/PSn00bSDK/blob/master/libpsn00b/psxspu/common.c#L28-L35) as part of the `libpsxspu` rewrite in v0.20 as a workaround. This is not going to be "fixed" (by e.g. replicating the behavior of the official SDK) as it works perfectly fine on real hardware and most up-to-date emulators, so I'm going to close this (at this point dead anyway) issue.
