### ISSUE TITLE
Examples: Builds fail due to LD error

### ISSUE THREAD

**Issue by GithubPrankster** [Lameguy64/PSn00bSDK#19]
_Cross-Compiler GCC Version_: 8.2.0 (also tried with 9.3.0)
_Cross-Compiler Binutils Version_: 2.31
_Operating System_: Debian 10 (Buster) Linux

Instructions for building the toolchain and SDK were all (hopefully) followed, _.mk_ versions set to 8.2.0. 
The errors mainly complain about:
`undefined reference to '__CTOR_LIST__'`
`undefined reference to '__DTOR_LIST__'`
Full log can be found [here](https://hatebin.com/ohiyiqzlqr).

**Comment by Lameguy64** [comment]
You need to modify elf32elmip.x in your toolchain directory and add __CTOR_LIST__ and __DTOR_LIST__ sections described in toolchain.txt

**Comment by GithubPrankster** [comment]
Thank you!
