### ISSUE TITLE
ZSF3 and ZSF4 during InitGeom might not be correct

### ISSUE THREAD

**Issue by Slamy** [Lameguy64/PSn00bSDK#27]
I've experimented a bit with your library and I think I found a bug.
In initgeom.s there is this InitGeom function.

```
	li   $v0, 0x155				# Set ZSF3 and ZSF4 defaults
	ctc2 $v0, $29
	li   $v0, 0x100
	ctc2 $v0, $30
```

I do believe that ZSF3 and ZSF4 have to be multplied by 4 to be accurate. It almost feels like an copy pasta error somehow.
During most of the examples you are performing a divison by 4 on Z during addPrim. It seems to be doubled here.
For example, if you use gte_rtps and gte_stsz you get the correct result while you get the result divided by 4 if you use gte_rtpt and gte_avsz3 even so all 3 points are at the same coordinate.

I just wanted to point that out. Please correct me if I'm wrong. I've stumbled on this issue as I've written something which uses billboards and polygon meshes in combination. The billboards have a Z coordinate which is 4 times bigger than the mesh.
I've combined your gte and billboard example to implement it.

**Comment by Lameguy64** [comment]
Those GTE register values for ZSF3 and ZSF4 are correct as the official libraries also sets those exact same values to the GTE. Most PS1 software usually just divides the result from AVSZ3/AVSZ4 further with bit shifts and I don't think many games set their own values to ZSF3/ZSF4.
