### ISSUE TITLE
Issue making tools (Windows)

### ISSUE THREAD

**Issue by ghost** [Lameguy64/PSn00bSDK#34]
I'm following the Windows installation process over in the README file and when compiling tools I get this error.

`make -C lzpack
make[1]: Entering directory '/c/psn00bsdk/tools/lzpack'
g++ -O2 -I/c/tinyxml2 -I../../libpsn00b -c main.cpp -o build/main.o
make[1]: g++: No such file or directory
make[1]: *** [makefile:32: build/main.o] Error 127
make[1]: Leaving directory '/c/psn00bsdk/tools/lzpack'
make: *** [makefile:7: lzpack] Error 2`

Probably the error suggests I haven't installed something important though I've done every single thing the installation guide told me to do. 

Thanks in advance. Hope you answer soon.

**Comment by Lameguy64** [comment]
Looks like you either don't have the GNU C++ compiler present somehow, or you don't have a path to the bin directory of your preferred MinGW compiler in your PATH environment.
