### ISSUE TITLE
Switching to (or adding support for) CMake

### ISSUE THREAD

**Issue by spicyjpeg** [Lameguy64/PSn00bSDK#37]
Would it make sense for PSn00bSDK to move to, or at least to add support for, a CMake-based build system?

In my PR (#36) to add support for dynamic linking I had to edit pretty much all Makefiles, and it became clear that they are not the easiest thing to maintain when there are almost 30 of them. I am already using CMake (modern 3.20, not the ancient 2.8 stuff) in my upcoming PS1 homebrew project and it's very easy to set up for cross-compiling, only requiring two files to be added. With those in place, a simple project's `CMakeLists.txt` would just be the following:

```cmake
cmake_minimum_required(VERSION 3.20)

set(CMAKE_TOOLCHAIN_FILE ../psn00bsdk-toolchain.cmake)
project(
	hello_world
	DESCRIPTION "PSn00bSDK CMake example"
	LANGUAGES C CXX ASM
)
include(../psn00bsdk-setup.cmake)

psn00bsdk_add_executable(main.exe main.c)
psn00bsdk_add_cd_image(hello_world.iso iso.xml.template)
# other macros could be defined e.g. for converting TIM images
```

If CMake support is added it would make sense to use CMake for building the libraries and examples as well, ditching the current Makefiles altogether. It would also help making the SDK easier to use with an IDE and/or under Windows, as CMake integrates with various IDEs and build systems that don't need Cygwin or MSys.

**Comment by Lameguy64** [comment]
I'll have to take time reevaluating cmake as I've had many issues trying to use it in the past. But you're right, the makefile method is a bit convoluted and messy in places that even I myself am starting to find it rather cumbersome to maintain.

Though another reason I'm sticking to makefiles in the meantime is so that PSn00bSDK projects can be built under Win9x coupled with the original msys, as I've managed to compile GCC 7.4.0 with MinGW GCC 4.7.2 which produces binaries that still work in 9x. This would come in handy once hardware communications with the DTL-H2000 have been figured out, and I have a feeling current versions of cmake would make use of dependencies that cannot be built with older GCC versions or make use of stupid MSVC calls not available in older versions of Windows. Though I suppose this can be avoided by simply writing the custom DTL-H2000 communication tools to work in Linux or one of the BSDs instead.

I propose you could make a fork that uses cmake exclusively so people who'd rather use cmake will use your fork, plus it'd also give me a chance to evaluate how it's all going to work myself and possibly merge it to mainline.

**Comment by saxbophone** [comment]
I too am interested in the use of a CMake-based build system. As unwieldy as its syntax can sometimes be, I have found it to be highly effective for setting common compiler flags and such in a concise way. I'm not too familiar with this project's Makefiles but at a glance, it looks like a lot is going on in terms of setting custom linker flags and what-not...

In regards to @Lameguy64 's comments about the usefulness of keeping the Makefiles for Win9x, it's possible to generate Makefiles with CMake. It would need testing to verify if the output achieves the same affects as the current Makefiles, though.

**Comment by Lameguy64** [comment]
It'd be incredibly clunky if I have to run cmake on a separate machine just to build it on 9x though. However, if cmake does not depend on too many needless dependencies that make use of newer WinAPI calls it might be possible to compile it for 9x.

**Comment by saxbophone** [comment]
Ah yes that's a good point!

Given that Kitware (CMake vendor) orients itself towards cross-platform dev, it wouldn't surprise me if the internals of CMake are very cross-platform. Then again, I'm not familiar with its source. From a quick glance at the current source code, the GUI appears to be Qt-based.

I appreciate this may be quite a large undertaking

**Comment by spicyjpeg** [comment]
Unfortunately any makefile or script generated by CMake depends heavily on CMake itself, mostly for mundane stuff like printing colored text but also for determining dependencies or building subprojects. That's in fact why makefiles generated by CMake on Windows don't need Cygwin: the CMake binary actually provides busybox-style implementations of several Unix commands (`cmake -E` prints out a list).

For DTL-H2000 owners I'd propose a completely different solution. Rather than trying to get the entire SDK to work on Windows 9x, I think some sort of server that exposes a remote GDB target for a modern machine to connect to would be more useful. This way modern IDEs and tools can be used with none of the hassle that comes with a 25-year-old PC, while still having the ability to debug on real hardware. Connecting Windows 9x to a network in 2021 might not seem a bright idea, but most consumer routers have options for limiting devices to LAN only (you'd probably want a network connection anyway to transfer files).

All this said, I have just published my CMake branch and opened #38, complete with initial support for CPack so we could eventually offer prebuilt packages and one-click installers. Let me know if anything needs fixing as I haven't yet tested it extensively.

**Comment by Lameguy64** [comment]
Well, this is coming from a guy who actually _tried_ to do Arduino programming with AVR assembly one time just to be unusual. Since the H2000 boards haven't been cracked yet it's not of major concern for now.

Once the H2000 boards have been cracked I've envisioned writing the tools to interface with it for Linux or NetBSD, though the latter's likely preferred as the operating system appears to be light enough to run snappily on older systems still. I imagine it'd be kinda like the PS2 TOOL development unit once such a thing comes to fruition.

**Comment by spicyjpeg** [comment]
I pushed a few more bugfixes and the CMake branch is now usable and fully functional, at least on Linux. I haven't yet been able to get the GCC toolchain to work on Windows, not even the precompiled one, however I managed to build the tools with MSVC after some patching (like I did with mkpsxiso).

Other than Windows compatibility, there are still a few more things to do before the branch can be merged:

* Test the SDK on macOS, especially on M1 processors. In theory everything should just work as CMake abstracts away OS-specific compilers and stuff, but I don't own a Mac for testing.
* Proofread all the new documentation I wrote, and maybe add proper tutorials on how to use the CMake macros and the dynamic linker.
* Merge Lameguy64/mkpsxiso#18 and edit the URL in `CMakeLists.txt` to point to the main mkpsxiso repo rather than my fork.

Regarding the DTL-H2000, I'd say it's probably best to focus on emulators and software-based loaders/debuggers that run on a regular PS1. The number of users owning *and actually willing* to use a devkit is very small, so getting into massive reverse engineering efforts on unreliable 1990's PC hardware is IMO not worth it. The top priority right now is making the SDK accessible and easy to install, 'cause nobody wants to use something that's even more complicated to set up than the ancient Sony stuff.

**Comment by saxbophone** [comment]
Is there any possibility of using Github-Actions to test on Linux, macOS and Windows? I've been able to get C++ stuff unit tested just fine on all three. The only tricky bit I can think of is the long amount of time and space required to build the toolchain, although I believe public open-source projects like these get a free CI credit allowance.

**Comment by spicyjpeg** [comment]
After almost a week of struggling I finally decided to get rid of all the auto-download and library finding stuff, which is clearly problematic on machines other than mine, and just include `mkpsxiso` and `tinyxml2` as git submodules instead. The CMake script in the tinyxml2 repo is no longer used, instead the sources are simply pulled from the submodule directory and compiled as part of the tools. I regret not doing this earlier.

With these changes in place I tried compiling PSn00bSDK on a fresh Windows 10 VM with only MSys2 installed (GCC, CMake, Ninja and git installed through MSys2, which now ships CMake 3.21 by the way). I encountered no issues other the `dynlink` example randomly crashing on DuckStation (which seems to have something to do with compiler options). Building packages and installing them in another VM worked fine as well, and `mkpsxiso` did not crash when building the examples.

There isn't much I can test beyond this. I'm not submitting PRs yet, however I published all changes in the [cmake branch](/spicyjpeg/PSn00bSDK/tree/cmake) so you can test them.

**Comment by saxbophone** [comment]
@spicyjpeg RE auto-downloading dependencies, have you heard of CPM? (https://github.com/cpm-cmake/CPM.cmake)

It works like a better version of `find_package()` and `FetchContent()` that can download dependencies through git and sets them up in the project tree like a CMake subproject.

**Comment by spicyjpeg** [comment]
@saxbophone: I started working on GitHub Actions CI now that PSn00bSDK is no longer broken (Lameguy64 merged my changes a few days ago, after I fixed some bugs that had been reported on the PSXDEV Discord server). The GCC toolchain is cached after being built: according to GitHub docs caches only expire after 7 days of inactivity, so this should prevent the toolchain from being recompiled unnecessarily most of the time.

Currently both the toolchain and SDK build successfully on both Windows and Linux. All builds are packaged up, bundled with the toolchain and uploaded as artifacts, so they can be downloaded from a commit's workflow run page (e.g. [this one](/spicyjpeg/PSn00bSDK/actions/runs/1513206464)) and installed locally for testing. I also added some code to publish these builds as releases when a tag is created, even though PSn00bSDK is still far from being stable enough for a proper release.

I am going to open another PR once I finish working on a few additional examples, mostly related to audio streaming and support for the Konami System 573 (PS1-based arcade platform).

**Comment by saxbophone** [comment]
@spicyjpeg That's wonderful, how impressive that the toolchain builds for three OSes in such a short amount of time in your CI config!

**Comment by spicyjpeg** [comment]
I'd say this issue can be closed now that both stable CMake support and GitHub Actions CI are in place. I'm going to delete my `actions` branch as usual and create a fresh one for the things I'm currently working on (the `psxspi` library and experimental audio transcoding tools).
