### ISSUE TITLE
PSXSDK compatibility/incooperability

### ISSUE THREAD

**Issue by IngwiePhoenix** [Lameguy64/PSn00bSDK#4]
A while ago, I was working on getting the (PSXSDK)[http://unhaut.x10host.com/psxsdk/] working on macOS and have since had it installed on my maschine to test it out. 

Seeing this SDK, I wonder how well it is compatible with it. The compiler that comes out of that SDK is like so:

```
Ingwie@Ingwies-Macbook-Pro.local ~ $ mipsel-unknown-elf-gcc -v
Es werden eingebaute Spezifikationen verwendet.
COLLECT_GCC=mipsel-unknown-elf-gcc
COLLECT_LTO_WRAPPER=/usr/local/psxsdk/libexec/gcc/mipsel-unknown-elf/7.2.0/lto-wrapper
Ziel: mipsel-unknown-elf
Konfiguriert mit: /Users/Ingwie/Work/Compilers/gcc-7.2.0/configure --disable-libada --disable-libssp --target=mipsel-unknown-elf --prefix=/usr/local/psxsdk --with-float=soft --with-newlib --without-headers --disable-libstdcxx --enable-languages=c,c++
Thread-Modell: single
gcc-Version 7.2.0 (GCC) 
Ingwie@Ingwies-Macbook-Pro.local ~ $ mipsel-unknown-elf-gcc --version
mipsel-unknown-elf-gcc (GCC) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
Dies ist freie Software; die Kopierbedingungen stehen in den Quellen. Es
gibt KEINE Garantie; auch nicht für MARKTGÄNGIGKEIT oder FÜR SPEZIELLE ZWECKE.
```

(Excuse all the german here, I tend to forget how to force GCC into outputting stuff in english...)

In theory, this should be able to compile this SDK - but what can I expect from it? PSXSDK offers CD-ROM access - so what if I was to use psn00bSDK's assembly based libraries but PSXSDK's CD-ROM APIs?

Kind regards,
Ingwie

**Comment by Lameguy64** [comment]
PSn00bSDK actually got controller and CD-ROM access via BIOS functions last month. I recently got a global IRQ handler like what the official SDK has that would make implementing better CD-ROM support possible with ease in the future. PSn00bSDK also has a much more stable VSync handler as well compared to PSXSDK's which used event handlers which are not appropriate for IRQ handling.
