### ISSUE TITLE
I can't compile, it says that there's an unknown command.

### ISSUE THREAD

**Issue by Lufims** [Lameguy64/PSn00bSDK#64]
When I try to compile it says that there's an unknown command on the cMakeLists.txt.

`CMake Error at CMakeLists.txt:14 (psn00bsdk_add_executable):
  Unknown CMake command "psn00bsdk_add_executable".`

**Comment by spicyjpeg** [comment]
You need to tell CMake where PSn00bSDK is by setting the `CMAKE_TOOLCHAIN_FILE` CMake variable to the full absolute path to `lib/libpsn00b/cmake/sdk.cmake` within the directory you installed PSn00bSDK into. You can do this in several ways:

- If you are using the `CMakePresets.json` file provided with the project template, create a new environment variable named `PSN00BSDK_LIBS` and set it to the full path to the `lib/libpsn00b` directory. The presets file will automatically configure CMake to use the SDK's toolchain file, with no need to change anything in your project.
- Alternatively, you can manually edit `CMakePresets.json` and replace the path in [this line](https://github.com/Lameguy64/PSn00bSDK/blob/master/template/CMakePresets.json#L14) with the full path to `sdk.cmake` on your machine. If you are on Windows, replace backslashes with forward slashes to make sure the JSON file can be parsed correctly.
- You can also pass `-DCMAKE_TOOLCHAIN_FILE="<path>"` to the CMake command line when configuring your project, or add `set(CMAKE_TOOLCHAIN_FILE "<path>")` before the `project()` command in `CMakeLists.txt`.

You can find more information about setting up the toolchain file and basic usage of presets [here](https://github.com/Lameguy64/PSn00bSDK/blob/master/doc/cmake_reference.md#setup).

**Comment by Lufims** [comment]
I did that, and now the issue is the other one that I posted, I created an environment variable to make it almost work
