### ISSUE TITLE
Could not find _gcc using the following names: mipsel-none-elf-gcc

### ISSUE THREAD

**Issue by Lufims** [Lameguy64/PSn00bSDK#65]
I'm almost giving up on compiling this, can someone help

I think the cause of this errors, is because during the instalation appeared a warning saying that it could not edit the path, because it was too long, so, if someone post the path entries (I think is that what is called), I could edit it mannualy.
![Screenshot_1](https://user-images.githubusercontent.com/73536178/201543752-0e7944ad-280c-461d-ab16-35e84abf567c.png)

**Comment by spicyjpeg** [comment]
The NSIS installer for version 0.19 seems to be broken. You can get around it by downloading the prebuilt v0.21 zip from [my fork](https://github.com/spicyjpeg/PSn00bSDK/releases/tag/v0.21) and extracting/installing it manually as detailed [here](https://github.com/Lameguy64/PSn00bSDK/blob/master/doc/installation.md#installing-a-prebuilt-release-recommended) (yes, it involves setting a couple of environment variables including the one I mentioned in the other issue you opened). You will have to invoke CMake from the command line, as the GUI does not fully support the Ninja generator backend.

By the way, please avoid opening multiple GitHub issues for the same reason (difficulties with installing the SDK in your case). Cluttering the issue tracker does not help anybody.

**Comment by Lufims** [comment]
> The NSIS installer for version 0.19 seems to be broken. You can get around it by downloading the prebuilt v0.21 zip from [my fork](https://github.com/spicyjpeg/PSn00bSDK/releases/tag/v0.21) and extracting/installing it manually as detailed [here](https://github.com/Lameguy64/PSn00bSDK/blob/master/doc/installation.md#installing-a-prebuilt-release-recommended) (yes, it involves setting a couple of environment variables including the one I mentioned in the other issue you opened). You will have to invoke CMake from the command line, as the GUI does not fully support the Ninja generator backend.
> 
> By the way, please avoid opening multiple GitHub issues for the same reason (difficulties with installing the SDK in your case). Cluttering the issue tracker does not help anybody.

I can't believe that was just setting the path environment variable, it worked now, and sorry for opening two issues, I thought I could not put different issues on the same issue, but now I need help with other thing, I'm using Visual Studio 16 2019 as a compiler, and the build folder just have this things, and not the .bin or .cue (sorry for that, there was only one other time that I tried to compile a program, so, i'm new with this)

**Comment by spicyjpeg** [comment]
You cannot use VS/MSBuild at all since it does not support the custom toolchain required to compile PS1 code; you need to use Ninja (included with the SDK) or one of CMake's Makefile generators instead. The default preset is already set up to use Ninja, so if you run the commands listed [here](https://github.com/Lameguy64/PSn00bSDK/blob/master/doc/installation.md#creating-a-project) the project should build correctly.

**Comment by Lufims** [comment]
> You cannot use VS/MSBuild at all since it does not support the custom toolchain required to compile PS1 code; you need to use Ninja (included with the SDK) or one of CMake's Makefile generators instead. The default preset is already set up to use Ninja, so if you run the commands listed [here](https://github.com/Lameguy64/PSn00bSDK/blob/master/doc/installation.md#creating-a-project) the project should build correctly.

I tried to install Ninja, but it says an error when I try to compile with cmake, and somehow a was able to create a CUE file with visual studio, but just the cue file was created.
![Screenshot_6](https://user-images.githubusercontent.com/73536178/201549135-a2a4d864-6999-4672-8b87-51be177dd1da.png)
![Screenshot_5](https://user-images.githubusercontent.com/73536178/201549141-a2ffceea-48da-498f-b1f8-203e00557d4b.png)
![Screenshot_7](https://user-images.githubusercontent.com/73536178/201549145-a2094797-577b-4c4b-872c-69e3d1f2fd60.png)

**Comment by spicyjpeg** [comment]
Ninja is bundled with the 0.21 release I linked before, just extract that in place of your existing installation. Also, I already told you not to use the CMake GUI and to run CMake from the command line instead, since the GUI does not support Ninja. I'd suggest you to avoid using VS as well, since configuring it to use PSn00bSDK's compiler instead of MSVC involves a significant number of configuration tweaks; use VS Code or a simple text editor instead and build from the command line.

**Comment by Lufims** [comment]
> Ninja is bundled with the 0.21 release I linked before, just extract that in place of your existing installation. Also, I already told you not to use the CMake GUI and to run CMake from the command line instead, since the GUI does not support Ninja. I'd suggest you to avoid using VS as well, since configuring it to use PSn00bSDK's compiler instead of MSVC involves a significant number of configuration tweaks; use VS Code or a simple text editor instead and build from the command line.

Ok, the Ninja worked, now I can't set the preset for the cmake, I'm using the command prompt now.
![Screenshot_9](https://user-images.githubusercontent.com/73536178/201550260-957c1d81-71d8-4205-a0e0-3e0ed1672cdb.png)

**Comment by Lufims** [comment]
> Ninja is bundled with the 0.21 release I linked before, just extract that in place of your existing installation. Also, I already told you not to use the CMake GUI and to run CMake from the command line instead, since the GUI does not support Ninja. I'd suggest you to avoid using VS as well, since configuring it to use PSn00bSDK's compiler instead of MSVC involves a significant number of configuration tweaks; use VS Code or a simple text editor instead and build from the command line.

I figured out how to use the command, i'm very dumb, it took me a long time to figure out how to use the command.
![Screenshot_10](https://user-images.githubusercontent.com/73536178/201552673-de55065f-773d-4d59-953f-016831f69ada.png)
![Screenshot_11](https://user-images.githubusercontent.com/73536178/201552676-1ad6ee8b-eb02-4551-8e1b-41c8e0ed9aad.png)

**Comment by Lufims** [comment]
> Ninja is bundled with the 0.21 release I linked before, just extract that in place of your existing installation. Also, I already told you not to use the CMake GUI and to run CMake from the command line instead, since the GUI does not support Ninja. I'd suggest you to avoid using VS as well, since configuring it to use PSn00bSDK's compiler instead of MSVC involves a significant number of configuration tweaks; use VS Code or a simple text editor instead and build from the command line.

I finnaly did it, but the emulator is not recognizing it
![Screenshot_12](https://user-images.githubusercontent.com/73536178/201553765-2fdccf64-118b-4464-9e6e-09380f9465c1.png)

**Comment by Lufims** [comment]
> > Ninja is bundled with the 0.21 release I linked before, just extract that in place of your existing installation. Also, I already told you not to use the CMake GUI and to run CMake from the command line instead, since the GUI does not support Ninja. I'd suggest you to avoid using VS as well, since configuring it to use PSn00bSDK's compiler instead of MSVC involves a significant number of configuration tweaks; use VS Code or a simple text editor instead and build from the command line.
> 
> I finnaly did it, but the emulator is not recognizing it ![Screenshot_12](https://user-images.githubusercontent.com/73536178/201553765-2fdccf64-118b-4464-9e6e-09380f9465c1.png)

I fixed it, I think
![Screenshot_14](https://user-images.githubusercontent.com/73536178/201554122-9f5399e1-337d-41e1-abda-8a3752112589.png)

**Comment by Lufims** [comment]
> Use a different emulator, as PCSXR is known to be highly inaccurate and additionally lacks debugging functionality. The following emulators are recommended for development:
> 
> * [DuckStation](https://github.com/stenzek/duckstation)
> * [pcsx-redux](https://github.com/grumpycoders/pcsx-redux)
> * [no$psx](https://problemkaputt.de/psx.htm)
> 
> If you are still getting stuck with building, try copying the project template as explained by the installation guide and building it as-is, without modifying anything (other than the path to the toolchain file if necessary). That should not give you any issues.

I just found out what was the issue, I was trying to PutDrawEnv with the &disp[db] argument (PutDrawEnv(&disp[db]), but now it's working fine
![Screenshot_15](https://user-images.githubusercontent.com/73536178/201640030-ebfba82f-689a-4973-b5ce-d08924e65e67.png)
