### ISSUE TITLE
Linux: Demo not working using PCSXR since commit `c800972`

### ISSUE THREAD

**Issue by Blaxar** [Lameguy64/PSn00bSDK#67]
I've been fiddling with the project at a surface level, mostly for the sake of building it and getting the demos running, all using the latest master (https://github.com/Lameguy64/PSn00bSDK/commit/4139331d233b7a962e747c5564fa68a285f81cc8).

The building step goes well once the correct MIPS gcc tool chain is correctly set, not much to report here, however: my experience at run time tells another story...

I load the iconic, freshly-built `n00bdemo.exe` using PCSXR and... nothing, black screen, but the emulator does not seems to report much meaningful info (compared to a successful run)

Fortunately: the last tagged release `v0.19` (some 49 commits ago...) builds AND runs successfully as far as I can tell, so I decided to try and find out when/where things went dark.

By manually performing binary search (yes) on the commit list between now and then to test what was resulting in a working demo and what wasn't: I've pinned down commit https://github.com/Lameguy64/PSn00bSDK/commit/c800972bc13ad0c7015b7d44fe9f124b719e792e as the faulty one

Much to my dismay: my non-existing MIPS-on-PSX knowledge does little to help me understand this and fix it myself, so instead I did the best I could by finding out where the issue originates from.

What more:

- I'm using PCSXR from the AUR repository on Arch Linux (`aur/pcsxr 1.9.95-2`) with BIOS `SCPH1001` if that helps.

- MIPS gcc toolchain was the one provided in the release build for `v0.19`, namely: `gcc-mipsel-none-elf-11.1.0-linux.zip`

- I've also tried loading the demo built from the latest master on ePSXe running on some Windows installation and same issue: black screen, that's why I'm assuming this issue is not emulator-specific, I've also tried different BIOSes (on both emulators): same thing.

- Just for clarity: I've tried loading actual ISOs of real officially-released games to ensure the emulators were working at all, turned out they were, so there's that.

This whole project looks insane and I'm counting on further fiddling with it (at least I know I have some working version of it), so if you want me to provide more info or test more things on my side regarding this issue: I'm all ears!

**Comment by alex-free** [comment]
PCSXR is not an accurate emulator. The recommend emulator is DuckStation or No $ PSX. Last time I tried the demos on those they worked great, as do real hardware. This probably will end up as a won't fix.

**Comment by Blaxar** [comment]
Thanks for the tip, I'll give DuckStation a shot then.

I still find the fact it used to work for PCSXR noteworthy, but then if the real hardware can still run it: I guess those two emulators I tried are objectively at fault then.
